# Generated by Django 5.2.1 on 2025-06-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=40, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the publisher.",
                        max_length=30,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="The address of the publisher.",
                        max_length=50,
                        verbose_name="Address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="The city where the publisher is located.",
                        max_length=60,
                        verbose_name="City",
                    ),
                ),
                (
                    "state_province",
                    models.CharField(
                        help_text="The state or province of the publisher.",
                        max_length=30,
                        verbose_name="State or Province",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="The country of the publisher.",
                        max_length=50,
                        verbose_name="Country",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        help_text="The publisher's website URL.", verbose_name="Website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("publication_date", models.DateField(verbose_name="Publication Date")),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="books.author"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.publisher",
                    ),
                ),
            ],
        ),
    ]
